name: Create DigitalOcean Droplet

on:
  workflow_dispatch:

jobs:
  create-droplet:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Upload to DigitalOcean
        run: |
          curl -X POST "https://api.digitalocean.com/v2/images" \
          -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{
                \"name\": \"Kali Linux\",
                \"url\": \"https://github.com/${{ github.repository }}/releases/download/disk.raw.gz\",
                \"distribution\": \"Debian\",
                \"region\": \"nyc3\", # Substitua pela região desejada
                \"description\": \"Kali Linux Custom Image\",
                \"tags\": [\"kali\"]
              }"

      - name: Create Droplet on DigitalOcean
        run: |
          curl -X POST "https://api.digitalocean.com/v2/droplets" \
          -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{
                \"name\": \"kali-droplet\",
                \"region\": \"nyc3\", # Substitua pela região desejada
                \"size\": \"s-1vcpu-1gb\",
                \"image\": \"custom-image-id\", # Substitua pelo ID ou slug da imagem
                \"ssh_keys\": [\"${{ secrets.DVPS_KEY }}\"],
                \"backups\": false,
                \"ipv6\": true,
                \"tags\": [\"kali-droplet\"]
              }"
