name: Create DigitalOcean Droplet

on:
  workflow_dispatch:

jobs:
  create-droplet:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get Custom Image ID
        id: get-image-id
        run: |
          set -e
          response=$(curl -s -w "\n%{http_code}" -X GET "https://api.digitalocean.com/v2/images?private=true" \
            -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}")
          
          response_body=$(echo "$response" | head -n -1)
          response_code=$(echo "$response" | tail -n 1)

          if [ "$response_code" -ne 200 ]; then
            echo "❌ Error fetching custom images. HTTP Code: $response_code"
            echo "API Response: $response_body"
            exit 1
          fi

          image_id=$(echo "$response_body" | jq -r '.images[] | select(.name=="kali-linux") | .id')
      
          if [ -z "$image_id" ]; then
            echo "❌ Unable to find the custom image 'kali-linux'."
            echo "API Response: $response_body"
            exit 1
          fi
      
          echo "Custom image ID found: $image_id"
          echo "image_id=$image_id" >> $GITHUB_ENV

      - name: Create Droplet on DigitalOcean
        run: |
          set -e
          response=$(curl -s -w "%{http_code}" -o response.json -X POST "https://api.digitalocean.com/v2/droplets" \
            -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
                  \"name\": \"kali-droplet\",
                  \"region\": \"nyc3\",
                  \"size\": \"s-1vcpu-1gb\",
                  \"image\": \"${{ env.image_id }}\",
                  \"ssh_keys\": [${{ secrets.DVPS_KEY }}],
                  \"backups\": false,
                  \"ipv6\": true,
                  \"tags\": [\"kali-droplet\"]
                }")
          
          response_code=$(tail -n 1 <<< "$response")
          if [ "$response_code" -ne 200 ] && [ "$response_code" -ne 202 ]; then
            echo "❌ Error creating the Droplet! HTTP Code: $response_code"
            cat response.json
            exit 1
          fi

          echo "Droplet created successfully!"
